arch: resnet50
batch_size: 32
csv: null
data: FairFace
dist_backend: nccl
dist_url: tcp://localhost:12345
distributed: false
epochs: 50
gpu: null
img_size: null
initial_checkpoint: null
log_interval: 50
lr: 0.01
mean: null
multi: false
num_classes: 1000
output: ''
patience_epochs: 5
pretrained: false
rank: 0
resume: null
seed: 42
start_epoch: 0
std: null
test_split: 0.4
threshold: 0.5
val_csv: null
vdata: null
workers: 4
world_size: 1
